// <auto-generated />
using Balta.Localizacao.MVVM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balta.Localizacao.MVVM.Data.Migrations
{
    [DbContext(typeof(LocalizacaoDbContex))]
    [Migration("20231218173558_IbgeCityNotUnique")]
    partial class IbgeCityNotUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Balta.Localizacao.MVVM.Domain.Models.IbgeModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(7)
                        .HasColumnType("char")
                        .HasColumnOrder(1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnOrder(3);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_IBGE");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_IBGE_City");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_IBGE_Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_IBGE_State");

                    b.ToTable("IBGE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
